language: generic
sudo: required
services:
    - docker
before_install:
    - docker build -t nandagopan/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true nandagopan/docker-react npm run test