language: generic
sudo: required
services:
    - docker
before_install:
    - docker build -t nandagopan/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true nandagopan/docker-react npm run test

#http://dockerreact-env.eba-phkywufe.us-east-1.elasticbeanstalk.com/
#arn:aws:s3:::elasticbeanstalk-us-east-1-240898402006

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-240898402006"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY